---
- name: Deploy Scientific Calculator Locally
  hosts: localhost
  connection: local
  vars:
    docker_image: "adithya952/scientific-calculator:latest"
    container_name: "calculator-app"

  tasks:
    - name: Pull latest image from Docker Hub
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull
        force_source: yes

    - name: Stop and remove old container if it exists
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent

    - name: Run the new container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        interactive: yes
        tty: yes
        # ports:
        #   - "8080:8080"